"""
# Stage 05 Wave Characterization
"""

from pathlib import Path
configfile: Path('configs') / 'config_template.yaml'
include: Path() / '..' / 'utils' / 'Snakefile'

#### Housekeeping ####

def measures_output(wildcards):
    return [OUTPUT_DIR / m / str(config.EVENT_NAME + "_" + m + ".csv")
            for m in config.MEASURES]

if config.EVENT_NAME == 'wavemodes':
    config.MEASURES = [m for m in config.MEASURES if m not in
                       ['label_planar', 'time_stamp', 'inter_wave_interval']]

#### UTILITY BLOCKS ####

use rule template as all with:
    input:
        check = OUTPUT_DIR / 'input.check',
        data = measures_output,
        script = SCRIPTS / 'merge_dataframes.py'
    params:
        params()
    output:
        OUTPUT_DIR / config.STAGE_OUTPUT,
        output_img = OUTPUT_DIR / 'overview_measures.html'

#### CHARACTERIZATION BLOCKS ####

use rule template as compute_measure with:
    input:
        data = config.STAGE_INPUT,
        script = SCRIPTS / str('{rule_measure}' + ".py")
    params:
        params(config.__dict__)
    output:
        Path('{dir}') / '{rule_measure}' / str(config.EVENT_NAME + "_" + '{rule_measure}' + ".csv"),
        output_img = Path('{dir}') / '{rule_measure}'
                      / str(config.EVENT_NAME + "_" + '{rule_measure}' + "." + config.PLOT_FORMAT)
