# Data path to be appended to data_path (see settings)
PATH: 'IDIBAPS'

# Name of the .smr data file
FILENAME: ['161101_rec07_Spontaneous_RH']

SAVE_IMAGE_FORMAT: 'png'

# min and max of frequency band in Hz
FREQ_BAND: [200, 1500]

# Minimal duration of a state to be detected
# in bins of the estimated MUA signal.
# MUA binsize ~ MIN_FREQ_BAND / sampling_rate^2
MIN_STATE_DURATION: 3

# Threshold for detecting up states;
# the threshold can either have a fixed value across channels
# (measures from center of fitted Gaussian)
# or be set in units of sigma
# (corresponding to respective Gaussian fit)
# FIXED_THRESHOLD has priority, 0 = None
FIXED_THRESHOLD: 0
SIGMA_THRESHOLD: 2

# Detrending: 0 - no detrending;
#             1 - mean detrending;
#             2 - mean and slope detrending (linear): this should be the default.
#             3 - quadratic detrending.
#             4 - cubic detrending.
DETRENDING_ORDER: 2

# Settings to be passed to the welch_psd function of elephant
PSD_OVERLAP: 0.5
PSD_FREQ_RES: 5 # Hz

# Window around state transitions to plot, in bins
SLOPE_WINDOW: 50

# METADATA
ELECTRODE_DISTANCE: 0.55 # mm
# PIXEL_SIZE: 0.55 #mm

# Key in the annotation dict, corresponding to the electrode location
ELECTRODE_ANNOTATION_NAME: 'channel_ids'

ELECTRODE_LOCATION:
    Visual Cortex: [3,6,7,8,9,14,15,16,17,23,24,25,26]
    Retrospenial Cortex: [31,32,33,34]
    Parietal Association Cortex: [5,13,22]
    Somatosensory Cortex: [4,10,11,12,19,20,21]
    Motor Cortex: [18,27,28,29,30]

# color scheme to match to figures in publication
ELECTRODE_COLOR:
    Visual Cortex: '#0C6BB1'
    Retrospenial Cortex: '#422F58'
    Parietal Association Cortex: '#01B24E'
    Somatosensory Cortex: '#F92600'
    Motor Cortex: '#EF6700'

# Dimensions of the grid where the electrodes/pixels are located
GRID_SIZE: [9,5]

# dictionary mapping the channels (ELECTRODE_ANNOTATION_NAME) to their coordiantes on the grid (GRID_SIZE)
NAME2COORDS:
    3:  (6,4)
    4:  (3,5)
    5:  (4,3)
    6:  (5,3)
    7:  (6,3)
    8:  (7,3)
    9:  (8,3)
    10: (1,2)
    11: (2,2)
    12: (3,2)
    13: (4,2)
    14: (5,2)
    15: (6,2)
    16: (7,2)
    17: (8,2)
    18: (0,1)
    19: (1,1)
    20: (2,1)
    21: (3,1)
    22: (4,1)
    23: (5,1)
    24: (6,1)
    25: (7,1)
    26: (8,1)
    27: (0,0)
    28: (1,0)
    29: (2,0)
    30: (3,0)
    31: (4,0)
    32: (5,0)
    33: (6,0)
    34: (7,0)
