curation_script_inputs:
  data:
    class: Directory
    location: /work/users/koehler/cobrawap-cwl/hands_on_cobrawap/test_datasets/imaging_deep_anesthesia/data
  output: curation_script.nix
  sampling_rate: 25
  spatial_scale: 0.05
  data_name: imaging_deep_anesthesia
  annotations:
  - '{"technique": "calcium imaging", "doi": "10.25493/QFZK-FXS", "anesthetic": "ketamine-xylazine",
    "concentration": "100 & 10 mg/kg", "model_type": "WT"}'
  array_annotations: null
  kwargs: null
  t_start: null
  t_stop: null
  orientation_top: ventral
  orientation_right: lateral
check_input_inputs:
  output: input.check
plot_traces_inputs:
  output_img: trace_imaging_deep_anesthesia.png
  plot_tstart: 0
  plot_tstop: 10
  plot_channels:
  - 4040
  - 5050
  - 6060
