# Calcium Imaging dataset "LENS_170110_mouse2"

DATA_NAME: 'LENS_170110_mouse2'

# path to folder with numbered .tif images
DATA_PATH: '/home/rgutzen/Sciebo/own/Data/WaveScalES/LENS/170110_mouse2_deep/t1'

# pixel size
SPATIAL_SCALE: 0.05  # mm

SAMPLING_RATE: 25  # Hz

ANNOTATIONS:
    experimental_lab: 'Pavone lab, Florence'
