# Config file for Stage 5 - Wave Characterization

# Name of stage, must be identical with folder name
STAGE_NAME: 'stage05_wave_characterization'

# The profile name is the key for this parameter configuration. Results are stored in output_path/<PROFILE>/ (output_path is defined in settings.py)
PROFILE: 'dataset_key'

# Name of the output file
STAGE_OUTPUT: 'measures.csv'

# Plotting parameters
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNELS: 'None'  # int or None. default 'None' -> randomly selected
PLOT_FORMAT: 'png'

# Measures to compute
<<<<<<< HEAD
# 'label_planar', 'velocity_planar', 'direction_planar'
MEASURES: ['label_planar', 'velocity_planar', 'direction_planar']
=======
# 'label_planar', 'velocity_planar', 'direction_planar', 'inter_wave_interval', 'time_stamp', 'duration', 'number_of_triggers'
MEASURES: ['inter_wave_interval', 'label_planar', 'velocity_planar', 'direction_planar']
>>>>>>> 1b82ec0e43e45e9e4b9a01ffcef7fb650cf0d575

# Label Planar
##############
ALIGNMENT_THRESHOLD: 0.9

# Direction Planar
##################
# tigger_interolation, optical_flow
DIRECTION_METHOD: 'optical_flow'
