# Config file for Stage 4 - Wavefront Detection

# Name of stage, must be identical with folder name
STAGE_NAME: 'stage04_wavefront_detection'

# Name of the output file
STAGE_OUTPUT: "waves.nix"

# File format in which all intermediate neo objects are stored
NEO_FORMAT: 'nix'

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True

# Plotting parameters
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNELS: 'None'  # int or None. default 'None' -> randomly selected
PLOT_FORMAT: 'png'

# Tigger Filter
###############
TRIGGER_FILTER: [] # ToDo

# Wavefront Filter
##################
WAVEFRONT_FILTER: [] # ToDo

# Wavefront Clustering
######################
# Using sklearn.cluster.DBSCAN
METRIC: 'euclidean'
# eps, maximum distance between points to be neigbours
NEIGHBOUR_DISTANCE: 15
MIN_SAMPLES_PER_WAVE: 30
# Transformation factor from time dimension to space dimension (in the units the data is presented).
TIME_DIM: 250
