
STAGES:
    - 'stage01_data_entry'
    - 'stage02_processing'
    - 'stage03_trigger_detection'
    - 'stage04_wavefront_detection'
    - 'stage05_wave_characterization'

# Plot settings
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNEL: 1  # int, list of ints, or 'None' (default) -> picks channel by random
PLOT_FORMAT: '.png'

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True
