"""
# Stage 05 Channel-wise Wave Characterization
"""

from pathlib import Path
configfile: Path('configs') / 'config_template.yaml'
include: Path() / '..' / 'utils' / 'Snakefile'

#### Housekeeping ####

def measures_output(wildcards):
    return [OUTPUT_DIR / measure / str(config.EVENT_NAME + "_" + measure + ".csv")
            for measure in config.MEASURES]

if config.EVENT_NAME == 'wavemodes':
    config.MEASURES = [m for m in config.MEASURES if m not in
                        ['inter_wave_interval_local', 'flow_direction_local']]

def input(wildcards):
    spatial_measures = ['velocity_local', 'direction_local']
    if wildcards.measure in spatial_measures:
        return rules.spatial_derivative.output
    else:
        return config.STAGE_INPUT

ruleorder: spatial_derivative > velocity_local > direction_local

#### UTILITY BLOCKS ####

use rule template as all with:
    input:
        check = OUTPUT_DIR / 'input.check',
        data = measures_output,
        script = SCRIPTS / 'merge_dataframes.py'
    params:
        params(merge_key = ['channel_id', str(config.EVENT_NAME + "_id")])
    output:
        OUTPUT_DIR / config.STAGE_OUTPUT,
        output_img = OUTPUT_DIR / 'overview_measures.html'

#### CHARACTERIZATION BLOCKS ####

use rule template as spatial_derivative with:
    input:
        data = config.STAGE_INPUT,
        script = SCRIPTS / 'spatial_derivative.py',
    params:
        params(kernel=config.KERNEL, interpolate=config.INTERPOLATE, smoothing=config.SMOOTHING,
               output_img_name = config.EVENT_NAME + "_spatial_derivative_wave0." + config.PLOT_FORMAT),
    output:
        OUTPUT_DIR / 'spatial_derivative'
                      / str(config.EVENT_NAME + "_spatial_derivative.csv"),
        output_img_dir = directory(OUTPUT_DIR / 'spatial_derivative'
                                   / str(config.EVENT_NAME + "_spatial_derivative_plots"))

use rule template as annotations with:
    input:
        data = config.STAGE_INPUT,
        script = SCRIPTS / "annotations.py"
    params:
        params(config.__dict__)
    output:
        OUTPUT_DIR / "annotations" / str(config.EVENT_NAME + "_annotations.csv")

use rule template as direction_local with:
    input:
        data = rules.spatial_derivative.output,
        script = SCRIPTS / "direction_local.py"
    params:
        params(config.__dict__)
    output:
        OUTPUT_DIR / "direction_local" / str(config.EVENT_NAME + "_direction_local.csv"),
        output_img = OUTPUT_DIR / "direction_local" / str(config.EVENT_NAME + "_direction_local." + config.PLOT_FORMAT)

use rule template as inter_wave_interval_local with:
    input:
        data = config.STAGE_INPUT,
        script = SCRIPTS / "inter_wave_interval_local.py"
    params:
        params(config.__dict__)
    output:
        OUTPUT_DIR / "inter_wave_interval_local" / str(config.EVENT_NAME + "_inter_wave_interval_local.csv"),
        output_img = OUTPUT_DIR / "inter_wave_interval_local" / str(config.EVENT_NAME + "_inter_wave_interval_local." + config.PLOT_FORMAT)

use rule template as velocity_local with:
    input:
        data = rules.spatial_derivative.output,
        script = SCRIPTS / "velocity_local.py"
    params:
        params(config.__dict__)
    output:
        OUTPUT_DIR / "velocity_local" / str(config.EVENT_NAME + "_velocity_local.csv"),
        output_img = OUTPUT_DIR / "velocity_local" / str(config.EVENT_NAME + "_velocity_local." + config.PLOT_FORMAT)
