ANNOTATIONS:
  experimental_lab: Pavone lab - Florence
ARRAY_ANNOTATIONS: None
CURATION_SCRIPT: curate_LENS_data.py
DATA_SETS:
  LENS_170111_mouse3_t1: /qst0/home1/homedirs/delucac/wavescales/pipeline/../Dataset/Ketamine/ketamine_25Hz/170111/mouse5/deep/t1
KWARGS: None
NEO_FORMAT: nix
ORIENTATION_RIGHT: lateral
ORIENTATION_TOP: ventral
PLOT_CHANNELS:
- 140
- 150
- 160
PLOT_FORMAT: png
PLOT_TSTART: 0
PLOT_TSTOP: 10
PROFILE: LENS
SAMPLING_RATE: 25
SPATIAL_SCALE: 0.05
STAGE_NAME: stage01_data_entry
STAGE_OUTPUT: data.nix
T_START: None
T_STOP: None
USE_LINK_AS_STAGE_OUTPUT: true
