# Config file for Stage 1 - Data Entry

# Name of stage, must be identical with folder name
STAGE_NAME: 'stage01_data_entry'

# The profile name is the key for this parameter configuration. Results are stored in output_path/<PROFILE>/ (output_path is defined in settings.py)
PROFILE: 'MF_LENS'

# Name of stage output file.
STAGE_OUTPUT: "data.nix"

# File format in which all intermediate neo objects are stored
NEO_FORMAT: 'nix'

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True

# Datasets which should be processed with identical settings.
# To set as key-value pairs
# Name_of_dataset: /path/to/data/files/
DATA_SETS:
    MF_Simulation_mouse2_t1: '/Users/chiaradeluca/Desktop/wavescalephant-APE/Dataset/MF_Simulation_Convoluted/DAMP_PERIOD_GridSearch_5/NuE_SIM_lognormal_t2_t3_1_1_DeltaAmp_Period_2.mat'

CURATION_SCRIPT: 'curate_MF_data.py'

# pixel size
SPATIAL_SCALE: 0.1  # mm

SAMPLING_RATE: 25  # Hz

DIM_X: 50 #pixel
DIM_Y: 50 #pixel

# time slice in s
# if None, the entire recording is used
T_START: None
T_STOP: None

# recommend top: ventral
ORIENTATION_TOP: 'ventral'
# recommended right: 'lateral' for right hemisphere, 'medial' for left hemisphere
ORIENTATION_RIGHT: 'lateral'

# Metadata
ANNOTATIONS:
    experimental_lab: 'Cristiano’s code'

ARRAY_ANNOTATIONS: 'None'

KWARGS: 'None'

# Plot settings
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNELS: [140, 150, 160]  # int, list of ints, or 'None' (default) -> picks channel by random
PLOT_FORMAT: 'png'
