
TRANSFORMATION_BLOCK: ['MUA_estimation']

DETECTION_BLOCK: 'Threshold'

# Fixed, Fitting/sigma, moment
THRESHOLD_METHOD: 'Fitting'

FITTING_PARAMS:
    FUNCTION: 'Gaussian'

MOMENT_PARAMS:
    ORDER: 2
    FACTOR: 3

# PARAMETERS FOR HILBERT DETECTION BLOCK
TRANSITION_PHASE: 1.570796

# FOR MINIMA DETECTION
FILTER_OPTIONS: []
