# Config file for Stage 3 - Trigger Detection
# Name of the output fileOUTPUT: "trigger_times.nix"
OUTPUT: 'trigger_times.nix'

PLOT_FORMAT: '.png'

# TRANSFORMATION BLOCKS (optional)
##################################
# The list determines the combination and order of blocks to transform the
# preprocessed signal. Default []
# Available Blocks: 'MUA_estimation', 'zscore', 'normalize'
TRANSFORMATION_BLOCKS: [MUA_estimation]

# DETECTION BLOCK
#################
# Available Blocks: 'threshold', 'hilbert_phase', 'minima'
DETECTION_BLOCK: 'threshold'

# BLOCK - MUA_estimation
########################
MUA_HIGHPASS_FREQ: 50  # in Hz
MUA_LOWPASS_FREQ: 1200  # in Hz
# Rate of the MUA signal. Must be <= the original sampling rate
MUA_RATE: 100 # in Hz (default: 'None', takes highpass_freq)
# Length of time slice (in s) to estimate the local power spectrum
# default 'None', takes minimum number of samples determined
# by the lower bound of the frequency band
FFT_SLICE: 0.1
PSD_OVERLAP: 0.5  # default (0.5)
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNEL: 12  # default 'None' -> randomly selected

# BLOCK - Threshold
###################
# Thresholding method: 'fixed', 'fitted', 'moment'
THRESHOLD_METHOD: 'fitted'

# Fitting Parameters
# available fit functions: 'Gaussian'
FIT_FUNCTION: 'Gaussian'
BIN_NUM: 100
SIGMA_FACTOR: 3

# Fixed Parameters
FIXED_THRESHOLD: 2

# Moment Parameters
MOMENT_ORDER: 2
MOMENT_FACTOR: 3

# BLOCK - Hilbert_phase
#######################
# Phase at which to define the upward transition [-pi, 0]
TRANSITION_PHASE: -1.570796

# BLOCK - Minima
################
# Number of neighbouring points which should be compared to define a local minimum.
MINIMA_ORDER: 3


# VIDEO SETTINGS
################
QUALITY: 5
SCALE_X: 720
SCALE_Y: 720
FPS: 10
