
PLOT_FORMAT: '.png'

# TRANSFORMATION BLOCKS (optional)
##################################
# The list determines the combination and order of blocks to transform the
# preprocessed signal. Default []
# Available Blocks: 'MUA_estimation',
TRANSFORMATION_BLOCKS: ['MUA_estimation']

# DETECTION BLOCK
#################
# Available Blocks: 'Threshold', 'Hilbert_phase', 'Minima'
DETECTION_BLOCK: 'Threshold'

# BLOCK - MUA_estimation
########################
MUA_HIGHPASS_FREQ: 200  # in Hz
MUA_LOWPASS_FREQ: 1500  # in Hz
MUA_RATE: 200  # in Hz
PSD_OVERLAP: 0.5  # in Hz
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNEL: 12  # default 'None' -> randomly selected

# BLOCK - Threshold
###################
# Thresdholding method: 'Fixed', 'Fitting', 'Moment'
THRESHOLD_METHOD: 'Fitting'

# Fitting Parameters
FITTING_PARAMS:
    FUNCTION: 'Gaussian'

# Fixed Parameters
FIXED_PARAMS:
    THRESDHOLD: 0

# Moment Parameters
MOMENT_PARAMS:
    ORDER: 2
    FACTOR: 3

# BLOCK - Hilbert_phase
#######################
# Phase at which to define the upward transition [-pi, 0]
TRANSITION_PHASE: -1.570796

# BLOCK - Minima
################
MIN_HIGHPASS_FREQ: 200  # in Hz
MIN_LOWPASS_FREQ: 1500  # in Hz
