DETECTION_BLOCK: threshold
FFT_SAMPLES: None
FIT_FUNCTION: Gaussian
FIXED_THRESHOLD: 2
INPUT_FILE: /home/rgutzen/ProjectsData/wave_analysis_pipeline/stage02_preprocessing/preprocessed_data.nix
MIN_HIGHPASS_FREQ: 200
MIN_LOWPASS_FREQ: 1500
MOMENT_FACTOR: 3
MOMENT_ORDER: 2
MUA_HIGHPASS_FREQ: 200
MUA_LOWPASS_FREQ: 1500
MUA_RATE: None
OUTPUT: trigger_times.nix
PLOT_CHANNEL: 12
PLOT_FORMAT: .png
PLOT_TSTART: 0
PLOT_TSTOP: 10
PSD_OVERLAP: 0.5
SIGMA_FACTOR: 3
THRESHOLD_METHOD: fixed
TRANSFORMATION_BLOCKS:
- MUA_estimation
TRANSITION_PHASE: -1.570796
