OUTPUT: 'LENSsim_data.nix'

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True

# Datasets which should be processed with identical settings.
# To set as key-value pairs
# Name_of_dataset: /path/to/data/files/
DATA_SETS:
    LENS_170110_mouse2_t1: '/home/rgutzen/Sciebo/own/Data/WaveScalES/LENSsimulated/SimulatedActivity.mat'

CURATION_SCRIPT: 'curate_LENS_simulation.py'

# pixel size
SPATIAL_SCALE: 0.05  # mm

SAMPLING_RATE: 25  # Hz

# time slice in s
# if None, the entire recording is used
T_START: 0
T_STOP: 10

# Metadata
ANNOTATIONS:

ARRAY_ANNOTATIONS: 'None'

KWARGS: 'None'

# Plot settings
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNEL: [1,2,3,4,5]  # int, list of ints, or 'None' (default) -> picks channel by random
PLOT_FORMAT: '.png'
