# Name of stage output file.
# Its path is relative to settings.output_path + stage_name
OUTPUT: "V4A_data.nix"

# If True (default), the output file of a stage is created as symbolic link
# to the last block output. If False, a duplicate is created (e.g. for cloud
# application, where sym-links are not supported).
USE_LINK_AS_STAGE_OUTPUT: True

# Datasets which should be processed with identical settings.
# To set as key-value pairs
# Name_of_dataset: /path/to/data/files/
DATA_SETS:
    y180116-land-m-001: '/home/rgutzen/Sciebo/own/Data/V4A/test_lfps/y180116-land-m-001.nix'

CURATION_SCRIPT: 'curate_V4A_data.py'

# Plot settings
PLOT_TSTART: 0  # in s
PLOT_TSTOP: 10  # in s
PLOT_CHANNEL: [1,2,3,4,5]  # int, list of ints, or 'None' (default) -> picks channel by random
PLOT_FORMAT: '.png'

# pixel size
SPATIAL_SCALE: 0.4  # mm

# specified in the data file
SAMPLING_RATE: 10000 # Hz

# Metadata
ANNOTATIONS:
    experimental_lab: 'Sanchez-Vives lab - Barcelona'
    grid_size: [10,10]

ARRAY_ANNOTATIONS: 'None'

# The keyword arguments are passed as key value pairs.
# Keywords must only contain letters, numbers, underscores, and spaces.
# Values can be strings, int, float, bool, or None.
# Values can also be aranged in 1D objects such as lists, or tuples
# It is possible to specify nested subdict.
KWARGS:
    ELECTRODE_ANNOTATION_NAME: 'channel_ids'
    NAME2COORDS:
        2: (0, 1)
        1: (0, 2)
        3: (0, 3)
        4: (0, 4)
        6: (0, 5)
        8: (0, 6)
        10: (0, 7)
        14: (0, 8)
        65: (1, 0)
        66: (1, 1)
        33: (1, 2)
        34: (1, 3)
        7: (1, 4)
        9: (1, 5)
        11: (1, 6)
        12: (1, 7)
        16: (1, 8)
        18: (1, 9)
        67: (2, 0)
        68: (2, 1)
        35: (2, 2)
        36: (2, 3)
        5: (2, 4)
        17: (2, 5)
        13: (2, 6)
        23: (2, 7)
        20: (2, 8)
        22: (2, 9)
        69: (3, 0)
        70: (3, 1)
        37: (3, 2)
        38: (3, 3)
        48: (3, 4)
        15: (3, 5)
        19: (3, 6)
        25: (3, 7)
        27: (3, 8)
        24: (3, 9)
        71: (4, 0)
        72: (4, 1)
        39: (4, 2)
        40: (4, 3)
        42: (4, 4)
        50: (4, 5)
        54: (4, 6)
        21: (4, 7)
        29: (4, 8)
        26: (4, 9)
        73: (5, 0)
        74: (5, 1)
        41: (5, 2)
        43: (5, 3)
        44: (5, 4)
        46: (5, 5)
        52: (5, 6)
        62: (5, 7)
        31: (5, 8)
        28: (5, 9)
        75: (6, 0)
        76: (6, 1)
        45: (6, 2)
        47: (6, 3)
        51: (6, 4)
        56: (6, 5)
        58: (6, 6)
        60: (6, 7)
        64: (6, 8)
        30: (6, 9)
        77: (7, 0)
        78: (7, 1)
        82: (7, 2)
        49: (7, 3)
        53: (7, 4)
        55: (7, 5)
        57: (7, 6)
        59: (7, 7)
        61: (7, 8)
        32: (7, 9)
        79: (8, 0)
        80: (8, 1)
        84: (8, 2)
        86: (8, 3)
        87: (8, 4)
        89: (8, 5)
        91: (8, 6)
        94: (8, 7)
        63: (8, 8)
        95: (8, 9)
        81: (9, 1)
        83: (9, 2)
        85: (9, 3)
        88: (9, 4)
        90: (9, 5)
        92: (9, 6)
        93: (9, 7)
        96: (9, 8)

# dictionary mapping the channels (ELECTRODE_ANNOTATION_NAME) to their coordiantes on the grid (grid_size)
