# Config file for Stage 5 - Wave Characterization

OUTPUT: 'measures.csv'

PLOT_FORMAT: '.png'

# Measure to compute
# 'velocity_planar', 'velocity_gradient', 'direction'
MEASURES: ['velocity_planer', 'velocity_gradient', 'direction']
